### ISSUE TITLE
JSON prototype risky

### ISSUE THREAD

**Issue by juliangruber** [deanlandolt/endo#1]
Say your JSON response ends up being a string, then this won't work:

``` js
var ret = 'foo'
ret.prototype.status = 200
Uncaught TypeError: Cannot set property 'status' of undefined
```

In the end, JSON responses can of course be served via streams as well, so I'd propose having and advocating an utility like

``` js
var ret = stream('foo');
ret.prototype.status = 200;
return ret;
```

with

``` js
function stream(json){
  var s = PassThrough();
  s.push(JSON.stringify(json));
  s.push(null);
  return s;
}
```

and only supporting stream responses.

**Comment by juliangruber** [comment]
On another note, using the prototype for this is a hack, although a good one :) Every framework deals with this differently, like express's

``` js
res.status(200);
```

or koa's

``` js
this.status = 200;
```

Using a return value for the body works nicely most of the cases, even redirects can be modeled with a lib like:

``` js
return redirect(url);
```

However using the prototype just seems like a big hack, so what if we used something like rack's signature for this:

``` js
return [200, { headers}, body];
```

See https://rack.github.io/

**Comment by deanlandolt** [comment]
You can use boxed strings `new String('....')` to status or headers on the proto, but I agree it's a hack. My thinking is it'd be so unusual to return raw string responses w/ anything but a 200 response, and you could always run your response through a helper (similar to the `redirect` helper you noted).

In general ISTM we're gonna want streams for almost all responses anyway -- I just wanted to make it really easy to return a stupid simple response -- but I guess we could always go with a more straight-forward signature and have a helper for the simple value responses like `return response.json({ foo: 'bar' }')`. That'd be a whole lot less hacky.

Re: rack -- yeah, I'd considered going with something like rack, or JSGI's response signature:

``` js
return {
  status: <int>,
  headers: <hash>,
  body: <string/buffer>
}
```

I figured it was probably overkill to require in every response for something geared explicitly toward JSON APIs, but it's a whole lot easier to just have one helper to add this stuff to simple responses than it would be to hack the shit out of prototypes like you'd have to do in my current design.

K, I'm sold. I'll fix this now and get it committed.

**Comment by deanlandolt** [comment]
Just pushed [this](https://github.com/deanlandolt/endo/commit/75a740c85482a998b284ea8b482291a41c744fe7) which cleans up the server implementation and moves to a more sane handler structure.

@juliangruber just reopen this issue if you'd like to see something different.

**Comment by juliangruber** [comment]
that looks a lot better to me :) and i just thought, if someone needs to do async work, they can do

``` js
var body = new PassThrough();

getData(function(err, data){
  if (err) return body.emit('error', err);
  body.push(JSON.stringify(data));
  body.push(null);
});

return body;
```

the only problem with this i can think of (using `.headers` instead of `.prototype.headers`) is when a stream already has an internal `.headers` object that you don't know about and not override.

**Comment by deanlandolt** [comment]
Yup, that's one way to do async -- though you could also just do this:

``` js
return new Promise(function (resolve, reject) {
  getData(function (err, data) {
    if (err) reject(err);
    else resolve({ body: data });
  });
});
```

We just `Promise.resolve` the data returned by the handler, which allows it to be a promise or plain data. This is even cleaner if your `getData` function already returns a promise:

``` js
return getData().then(function (data) {
    return { body: data };
});
```

You bring up a good point about streams possibly having a `headers` key somewhere on their prototype. Perhaps we could own-property test when extracting `status` and `headers` from stream objects?

**Comment by deanlandolt** [comment]
One more point: returning responses directly allows middleware-like functionality to be a lot more direct -- "middleware" is just a higher order function you wrap around a handler which can alter the request object on the way in and/or the response on the way out. No magical, non-linear chains of middeware necessary -- just functions.

**Comment by juliangruber** [comment]
> One more point: returning responses directly allows middleware-like functionality to be a lot more direct -- "middleware" is just a higher order function you wrap around a handler which can alter the request object on the way in and/or the response on the way out. No magical, non-linear chains of middeware necessary -- just functions.

that misses one point though, in which one middleware depends on the results of another, like for example

``` js
app.use(loadData())
app.use(toJSON())
app.use(logResponseSize())
```

**Comment by juliangruber** [comment]
> We just Promise.resolve the data returned by the handler

sounds good

**Comment by juliangruber** [comment]
> You bring up a good point about streams possibly having a headers key somewhere on their prototype. Perhaps we could own-property test when extracting status and headers from stream objects?

That only fixes the symptoms though, because if a stream has `.headers` and we overwrite that, the stream might not work any more. Seems like `return { body: stream }` is the only save way here.

**Comment by deanlandolt** [comment]
> That only fixes the symptoms though

True enough, but ISTM streams would typically have a pretty clean top level. But maybe I'm assuming too much. But meh -- still a hazard. Will commit a fix today that moves to the `{ body: stream }` style.

**Comment by deanlandolt** [comment]
> that misses one point though

What do you think about being able to provide a handler function that wraps all handlers with your "middleware chain"? That would solve the problem w/o any weird `use` magic.

**Comment by juliangruber** [comment]
tbh i didn't know "middleware" was part of endo, maybe we should start that part with an example that requires middleware like functionality?

**Comment by deanlandolt** [comment]
TBH it wasn't really...just something that occurred to me that we could do when you suggested using a more rack/wsgi/jsgi-like response structure :)

And it seems pretty easy to allow the config object to provide a handler function that gets passed the underlying endpoint handler "app" to delegate to, something like:

``` js
function handler(app) {
   return function (request) {
    // do stuff with request object
    return app(request)
  }
}
```

Or if you want to interact with the response:

``` js
function handler(app) {
  return function (request) {
    // do stuff with request object
    return Promise.resolve(app(request)).then(function (response) {
      // do stuff with response object
    })
  }
}
```

**Comment by deanlandolt** [comment]
As for examples of mw-like-functionality, logging, auth, and throttling are great examples.

We might also wrap individual handlers that are more restrictive than any default auth with little handlers to explicitly require some specific auth group be added to the request as part of the the default "auth" check (which might validate a JWT or something). Writing something up now.

**Comment by deanlandolt** [comment]
Though I should probably avoid using the word "middleware" as it implies a lot of conventional baggage that's not really in play here. What I'm describing is more like request handler _AOP_ (specifically, "around" advice).

**Comment by deanlandolt** [comment]
Closing this issue as we're no longer using **proto** hack.
